# Generated by Django 4.1 on 2022-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=b"I01\n", upload_to=""),
            preserve_default=b"I01\n",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=10, null=b"I01\n"),
            preserve_default=b"I01\n",
        ),
    ]
